id = "encore-zed"
name = "Encore"
version = "0.0.2"
schema_version = 1
authors = ["Maksim Shushkevich <m.e.shushkevich@yandex.com>"]
description = "Encore extension for Zed"
repository = "https://github.com/encore-language/encore-zed"

[grammars.encore]
repository = "https://github.com/encore-language/tree-sitter-encore"
commit = "260223aa01b8a2f6792036d5dd3ed538a967fda6"
