id = "encore-zed"
name = "Encore"
version = "0.0.7"
schema_version = 1
authors = ["Maksim Shushkevich <m.e.shushkevich@yandex.com>"]
description = "Encore extension for Zed"
repository = "https://github.com/encore-ecosystem/encore-zed"
languages = ["languages/encore"]
capabilities = []

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.encore]
repository = "https://github.com/encore-ecosystem/tree-sitter-encore"
commit = "5546230513d510fcf331862714926625cd22f3a0"

[language_servers.encore-lsp]
name = "Encore LSP"
languages = ["Encore"]

[language_servers.encore-lsp.language_ids]
Encore = "encore"
