id = "encore-zed"
name = "Encore"
version = "0.0.2"
schema_version = 1
authors = ["Maksim Shushkevich <m.e.shushkevich@yandex.com>"]
description = "Encore extension for Zed"
repository = "https://github.com/encore-language/encore-zed"

[grammars.encore]
repository = "https://github.com/encore-language/tree-sitter-encore"
commit = "e9fb9e75f2262be7725459490d769689ed5ec2d4"
